[package]
name = "zj-session"
version = "0.2.0"
authors = ["Cristian Dominguez", "Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

[dependencies]
zellij-tile = "0.43.1"
chrono = "0.4.0"
fuzzy-matcher = "0.3.7"
unicode-width = "0.1.10"
humantime = "2.1.0"
